// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"

	"gorm.io/gorm"

	"github.com/threeport/threeport/internal/kubernetes-runtime/mapping"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// KubernetesRuntimeInfraProvider indicates which infrastructure provider is being
// used to run the kubernetes cluster for the threeport control plane.
type KubernetesRuntimeInfraProvider string

const (
	KubernetesRuntimeInfraProviderKind = "kind"
	KubernetesRuntimeInfraProviderEKS  = "eks"
	KubernetesRuntimeInfraProviderOKE  = "oke"
	KubernetesRuntimeInfraProviderGKE  = "gke"
)

// SupportedInfraProviders returns all supported infra providers.
func SupportedInfraProviders() []KubernetesRuntimeInfraProvider {
	return []KubernetesRuntimeInfraProvider{
		KubernetesRuntimeInfraProviderKind,
		KubernetesRuntimeInfraProviderEKS,
		KubernetesRuntimeInfraProviderOKE,
		KubernetesRuntimeInfraProviderGKE,
	}
}

// beforeCreate validates the KubernetesRuntimeDefinition before create.
//
// Why: InfraProvider must be one of the values returned by SupportedInfraProviders.
func (k *KubernetesRuntimeDefinition) beforeCreate(tx *gorm.DB) error {
	infraProviders := SupportedInfraProviders()
	for _, provider := range infraProviders {
		if *k.InfraProvider == string(provider) {
			return nil
		}
	}
	return util.NewBadRequestError(
		fmt.Sprintf(
			"%s provider is not valid, valid providers: %s",
			*k.InfraProvider, infraProviders,
		),
	)
}

// beforeUpdate validates the KubernetesRuntimeDefinition before update.
//
// Why: InfraProvider and HighAvailability are immutable; changing either
// would orphan existing infrastructure.
func (k *KubernetesRuntimeDefinition) beforeUpdate(tx *gorm.DB) error {
	if tx.Statement.Changed("InfraProvider") {
		return util.NewBadRequestError(
			"kubernetes runtime definition infra provider cannot be changed after creation",
		)
	}
	if tx.Statement.Changed("HighAvailability") {
		return util.NewBadRequestError(
			"kubernetes runtime definition high availability cannot be changed after creation",
		)
	}
	return nil
}

// beforeDelete validates the KubernetesRuntimeDefinition before delete.
func (k *KubernetesRuntimeDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate validates the KubernetesRuntimeInstance before create.
//
// Why: Location must be one supported by the runtime mapping.
func (k *KubernetesRuntimeInstance) beforeCreate(tx *gorm.DB) error {
	if !mapping.ValidLocation(*k.Location) {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"location %s is not supported for a kubernetes runtime instance",
				*k.Location,
			),
		)
	}
	return nil
}

// beforeUpdate validates the KubernetesRuntimeInstance before update.
//
// Why: Location is immutable. Moving a runtime instance would orphan its cluster.
func (k *KubernetesRuntimeInstance) beforeUpdate(tx *gorm.DB) error {
	if tx.Statement.Changed("Location") {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"kubernetes runtime instances cannot be moved - location %s is immutable",
				*k.Location,
			),
		)
	}
	return nil
}

// beforeDelete validates the KubernetesRuntimeInstance before delete.
//
// Why: a runtime instance may not be removed while any workload instance still
// references it. Returns 400 with the requirement to remove dependents first.
func (k *KubernetesRuntimeInstance) beforeDelete(tx *gorm.DB) error {
	var workloadInstances []WorkloadInstance
	if result := tx.Where(
		&WorkloadInstance{KubernetesRuntimeInstanceID: k.ID},
	).Find(&workloadInstances); result.Error != nil {
		return fmt.Errorf(
			"failed to query workload instances for kubernetes runtime instance %s",
			*k.Name,
		)
	}

	if len(workloadInstances) > 0 {
		return util.NewBadRequestError(
			fmt.Sprintf(
				"kubernetes runtime instance %s cannot be deleted until workloads are removed",
				*k.Name,
			),
		)
	}

	return nil
}

// afterCreate runs after the KubernetesRuntimeDefinition is created.
func (k *KubernetesRuntimeDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the KubernetesRuntimeDefinition is updated.
func (k *KubernetesRuntimeDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the KubernetesRuntimeDefinition is deleted.
func (k *KubernetesRuntimeDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the KubernetesRuntimeInstance is created.
func (k *KubernetesRuntimeInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the KubernetesRuntimeInstance is updated.
func (k *KubernetesRuntimeInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the KubernetesRuntimeInstance is deleted.
func (k *KubernetesRuntimeInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
