// generated by 'threeport-sdk codegen api-version' - do not edit

package v1

var AttachedObjectReferenceTaggedFields = make(map[string]*FieldsByTag)
var WorkloadInstanceTaggedFields = make(map[string]*FieldsByTag)
