// generated by 'threeport-codegen controller' - do not edit

package controlplane

// The name and description of the NATS bucket used for control plane object locks
const (
	LockBucketName  = "controlPlaneLock"
	LockBucketDescr = "contains locks on control plane objects"
)
