---
builds:
  - id: tptctl
    binary: tptctl
    main: cmd/tptctl/main.go
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
  - id: threeport-sdk
    binary: threeport-sdk
    main: cmd/sdk/main.go
    env:
      - CGO_ENABLED=0
archives:
  - name_template: 'threeport_v{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
    wrap_in_directory: true
    allow_different_binary_count: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-snapshot-{{.ShortCommit}}"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^dev(\(.*\))?:'
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'
      - '^release(\(.*\))?:'
      - '^refactor(\(.*\))?:'
