---
before:
builds:
  - id: tptctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: cmd/tptctl/main.go
    binary: tptctl
  - id: threeport-sdk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: cmd/sdk/main.go
    binary: threeport-sdk
  - id: threeport-rest-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/rest-api/main.go
    binary: rest-api
  - id: threeport-database-migrator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/database-migrator/main.go
    binary: database-migrator
  - id: threeport-workload-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/workload-controller/main_gen.go
    binary: workload-controller
  - id: threeport-kubernetes-runtime-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/kubernetes-runtime-controller/main_gen.go
    binary: kubernetes-runtime-controller
  - id: threeport-aws-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/aws-controller/main_gen.go
    binary: aws-controller
  - id: threeport-gateway-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/gateway-controller/main_gen.go
    binary: gateway-controller
  - id: threeport-control-plane-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/control-plane-controller/main_gen.go
    binary: control-plane-controller
  - id: threeport-helm-workload-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/helm-workload-controller/main_gen.go
    binary: helm-workload-controller
  - id: threeport-terraform-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/terraform-controller/main_gen.go
    binary: terraform-controller
  - id: threeport-observability-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/observability-controller/main_gen.go
    binary: observability-controller
  - id: threeport-secret-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/secret-controller/main_gen.go
    binary: secret-controller
  - id: threeport-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: cmd/agent/main.go
    binary: agent
archives:
  - name_template: '{{ .Binary }}_v{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
    wrap_in_directory: true
    strip_binary_directory: true
    allow_different_binary_count: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-snapshot-{{.ShortCommit}}"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^dev(\(.*\))?:'
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'
      - '^release(\(.*\))?:'
      - '^refactor(\(.*\))?:'
dockers:
  - image_templates:
      - 'ghcr.io/threeport/threeport-rest-api:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-rest-api:latest'
    dockerfile: cmd/rest-api/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-database-migrator:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-database-migrator:latest'
    dockerfile: cmd/database-migrator/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-workload-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-workload-controller:latest'
    dockerfile: cmd/workload-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-kubernetes-runtime-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-kubernetes-runtime-controller:latest'
    dockerfile: cmd/kubernetes-runtime-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-aws-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-aws-controller:latest'
    dockerfile: cmd/aws-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-gateway-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-gateway-controller:latest'
    dockerfile: cmd/gateway-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-control-plane-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-control-plane-controller:latest'
    dockerfile: cmd/control-plane-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-helm-workload-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-helm-workload-controller:latest'
    dockerfile: cmd/helm-workload-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-terraform-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-terraform-controller:latest'
    dockerfile: cmd/terraform-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-control-plane-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-control-plane-controller:latest'
    dockerfile: cmd/control-plane-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-observability-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-observability-controller:latest'
    dockerfile: cmd/observability-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-secret-controller:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-secret-controller:latest'
    dockerfile: cmd/secret-controller/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/threeport/threeport-agent:v{{ .Version }}'
      - 'ghcr.io/threeport/threeport-agent:latest'
    dockerfile: cmd/agent/image/Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=Apache2"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"

