FROM golang:alpine

RUN apk add --no-cache --update \
    build-base
RUN go install github.com/cosmtrek/air@latest

RUN mkdir /threeport
COPY ./go.mod /threeport/go.mod
WORKDIR /threeport
RUN go mod download

ADD . /threeport

ENTRYPOINT ["air", \
    "-c", "/threeport/cmd/ethereum-node-controller/image/air.toml", \
    "-build.cmd", "go build -o bin/threeport-ethereum-node-controller cmd/ethereum-node-controller/main.go", \
    "-build.bin", "./bin/threeport-ethereum-node-controller"]

