// generated by 'threeport-codegen controller' - do not edit

package aws

// The name and description of the NATS bucket used for aws object locks
const (
	LockBucketName  = "awsLock"
	LockBucketDescr = "contains locks on aws objects"
)
