FROM golang:1.20-alpine as base
RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    mv /go/bin/dlv /usr/local/bin

FROM gcr.io/distroless/static:nonroot
COPY --from=base /usr/local/bin/dlv /usr/local/bin/dlv
COPY bin/threeport-agent /threeport-agent
USER 65532:65532

ENTRYPOINT ["/threeport-agent"]
