FROM golang:1.19-alpine

RUN apk update && apk add git
RUN go install github.com/cosmtrek/air@latest

RUN mkdir /threeport
WORKDIR /threeport

ENTRYPOINT ["air", \
    "-c", "/threeport/cmd/agent/image/air.toml", \
    "-build.cmd", "go build -o bin/threeport-agent cmd/agent/main.go", \
    "-build.bin", "./bin/threeport-agent"]

