// generated by 'threeport-sdk gen controller' - do not edit

package terraform

// The name and description of the NATS bucket used for terraform object locks
const (
	LockBucketName  = "terraformLock"
	LockBucketDescr = "contains locks on terraform objects"
)
