FROM golang:1.19-alpine

RUN apk update && apk add git
RUN go install github.com/cosmtrek/air@latest

RUN mkdir /threeport
WORKDIR /threeport

ENTRYPOINT ["air", \
    "-c", "/threeport/cmd/kubernetes-runtime-controller/image/air.toml", \
    "-build.cmd", "go build -o bin/threeport-kubernetes-runtime-controller cmd/kubernetes-runtime-controller/main_gen.go", \
    "-build.bin", "./bin/threeport-kubernetes-runtime-controller"]

