// generated by 'threeport-sdk gen' for API routes boilerplate' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "github.com/threeport/threeport/pkg/api-server/v0/handlers"
	v0 "github.com/threeport/threeport/pkg/api/v0"
)

// HelmWorkloadDefinitionRoutes sets up all routes for the HelmWorkloadDefinition handlers.
func HelmWorkloadDefinitionRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET("/helm-workload-definitions/versions", h.GetHelmWorkloadDefinitionVersions)

	e.POST(v0.PathHelmWorkloadDefinitions, h.AddHelmWorkloadDefinition)
	e.GET(v0.PathHelmWorkloadDefinitions, h.GetHelmWorkloadDefinitions)
	e.GET(v0.PathHelmWorkloadDefinitions+"/:id", h.GetHelmWorkloadDefinition)
	e.PATCH(v0.PathHelmWorkloadDefinitions+"/:id", h.UpdateHelmWorkloadDefinition)
	e.PUT(v0.PathHelmWorkloadDefinitions+"/:id", h.ReplaceHelmWorkloadDefinition)
	e.DELETE(v0.PathHelmWorkloadDefinitions+"/:id", h.DeleteHelmWorkloadDefinition)
}

// HelmWorkloadInstanceRoutes sets up all routes for the HelmWorkloadInstance handlers.
func HelmWorkloadInstanceRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET("/helm-workload-instances/versions", h.GetHelmWorkloadInstanceVersions)

	e.POST(v0.PathHelmWorkloadInstances, h.AddHelmWorkloadInstance)
	e.GET(v0.PathHelmWorkloadInstances, h.GetHelmWorkloadInstances)
	e.GET(v0.PathHelmWorkloadInstances+"/:id", h.GetHelmWorkloadInstance)
	e.PATCH(v0.PathHelmWorkloadInstances+"/:id", h.UpdateHelmWorkloadInstance)
	e.PUT(v0.PathHelmWorkloadInstances+"/:id", h.ReplaceHelmWorkloadInstance)
	e.DELETE(v0.PathHelmWorkloadInstances+"/:id", h.DeleteHelmWorkloadInstance)
}
