package apiobjectmanager

import (
	"fmt"
	"os"
	"strings"

	. "github.com/dave/jennifer/jen"
	"github.com/threeport/threeport/internal/sdk"
)

func CreateNewAPIFile(controllerDomain string, apiObjects []*sdk.APIObject, apiFilePath string) error {
	f := NewFile("v0")
	f.HeaderComment("generated by 'threeport-sdk create api-object'")
	f.Line()
	f.HeaderComment("//go:generate threeport-sdk gen api-model --filename $GOFILE --package $GOPACKAGE")

	// Determine if any objects within this controller domain need reconcilliation
	needReconcilers := false
	for _, obj := range apiObjects {
		if obj.Reconcilable != nil && *obj.Reconcilable {
			needReconcilers = true
			break
		}
	}

	if needReconcilers {
		f.HeaderComment("//go:generate threeport-sdk gen controller --filename $GOFILE")
	}

	// Create the necessary structs for each object in the domain api file
	for _, obj := range apiObjects {
		structFields := make([]Code, 0)
		structFields = append(structFields, Id("Common").Tag(map[string]string{"swaggerignore": "true", "mapstructure": ",squash"}))

		// Infer if object needs to be reconciled and add appropiate markers and fields
		if obj.Reconcilable != nil && *obj.Reconcilable {
			f.Comment("// +threeport-sdk:reconciler")
			structFields = append(structFields, Id("Reconciliation").Tag(map[string]string{"mapstructure": ",squash"}))

			// Infer if the object is an instance or a definition and add appropiate fields for it
			if strings.HasSuffix(strings.ToLower(*obj.Name), "instance") {
				structFields = append(structFields, Id("Instance").Tag(map[string]string{"mapstructure": ",squash"}))
			}
			if strings.HasSuffix(strings.ToLower(*obj.Name), "definition") {
				structFields = append(structFields, Id("Definition").Tag(map[string]string{"mapstructure": ",squash"}))
			}
		}

		// Define the struct for the object
		f.Type().Id(*obj.Name).Struct(structFields...)
		f.Line()
	}

	// write code to file
	file, err := os.OpenFile(apiFilePath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
	if err != nil {
		return fmt.Errorf("failed to open file to write generated code for %s api file: %w", controllerDomain, err)
	}
	defer file.Close()
	if err := f.Render(file); err != nil {
		return fmt.Errorf("failed to render generated source code for %s api file: %w", controllerDomain, err)
	}
	fmt.Printf("code generation complete for %s api file\n", controllerDomain)

	return nil
}

func CreateControllerDirs(controllerDomain string, rootDir string) error {
	// controller domain name is in snake case and the dir name has to be kebab case
	kebabDomain := strings.ReplaceAll(controllerDomain, "_", "-")
	controllerName := fmt.Sprintf("%s-controller", controllerDomain)

	// create dir for controller cmd
	if err := os.Mkdir(fmt.Sprintf("cmd/%s", controllerName), 0755); err != nil {
		return fmt.Errorf("could not create cmd dir for controller domain: %s, %w", kebabDomain, err)
	}

	// create internal dir for reconcilers
	if err := os.Mkdir(fmt.Sprintf("internal/%s", kebabDomain), 0755); err != nil {
		return fmt.Errorf("could not create internal dir for controller domain: %s, %w", kebabDomain, err)
	}

	fmt.Printf("dir creation complete for controller %s\n", controllerName)
	return nil
}
