FROM golang:1.20-alpine

RUN apk update && apk add git
RUN go install github.com/cosmtrek/air@latest && \
    mv /go/bin/air /usr/local/bin

RUN mkdir /threeport
WORKDIR /threeport

ENTRYPOINT ["/usr/local/bin/air", \
    "-c", "/threeport/cmd/control-plane-controller/image/air.toml", \
    "-build.cmd", "go build -o bin/threeport-control-plane-controller cmd/control-plane-controller/main_gen.go", \
    "-build.bin", "./bin/threeport-control-plane-controller"]

