FROM golang:1.20-alpine

RUN apk update && apk add git
RUN go install github.com/cosmtrek/air@latest && \
    cp /go/bin/air /usr/local/bin

RUN mkdir /threeport
WORKDIR /threeport

ENTRYPOINT ["/usr/local/bin/air", \
    "-c", "/threeport/cmd/rest-api/image/air.toml", \
    "-build.cmd", "go build -o bin/threeport-rest-api cmd/rest-api/main.go", \
    "-build.bin", "./bin/threeport-rest-api"]

