FROM golang:1.19-alpine

RUN apk add --no-cache --update \
    build-base
RUN go install github.com/cosmtrek/air@latest

RUN mkdir /threeport
WORKDIR /threeport
COPY ./go.mod /threeport/go.mod
RUN go mod download

ADD . /threeport

ARG BUILD_CACHE_FLAG
ENV BUILD_CACHE_FLAG=${BUILD_CACHE_FLAG}

CMD ["air", \
    "-c", "/threeport/cmd/rest-api/image/air.toml", \
    "-build.cmd", "go build ${BUILD_CACHE_FLAG} -o bin/threeport-rest-api cmd/rest-api/main.go", \
    "-build.bin", "./bin/threeport-rest-api"]

