FROM golang:alpine
RUN mkdir /threeport
ADD . /threeport
WORKDIR /threeport
RUN apk add --no-cache --update \
    build-base \
    curl
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air
ENTRYPOINT ["air", \
    "-c", "/threeport/cmd/rest-api/image/air.toml", \
    "-build.cmd", "go build -a -o bin/threeport-rest-api cmd/rest-api/main.go", \
    "-build.bin", "./bin/threeport-rest-api"]

