ARG ARCH
ARG BINARY

# base target
FROM golang:1.20-alpine as base
RUN apk update && apk add git
RUN mkdir /threeport
WORKDIR /threeport

# delve target
FROM base as delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    mv /go/bin/dlv /usr/local/bin

# live-reload development target
FROM delve as live-reload-dev
RUN go install github.com/cosmtrek/air@latest && \
    mv /go/bin/air /usr/local/bin

# static development target
FROM delve as static-dev
COPY bin/threeport-${BINARY}-${ARCH} /threeport-${BINARY}

ENTRYPOINT ["/threeport-${BINARY}"]