FROM golang:1.20-alpine

RUN apk update && apk add git
RUN go install github.com/cosmtrek/air@latest && \
    mv /go/bin/air /usr/local/bin

RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    mv /go/bin/dlv /usr/local/bin

RUN mkdir /threeport
WORKDIR /threeport
