FROM golang:1.22-alpine as builder
ARG TERRAFORM_VERSION=1.7.3
WORKDIR /
# download terraform
RUN apk update && apk add --no-cache ca-certificates wget unzip
RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /terraform /usr/local/bin/
COPY terraform-controller /terraform-controller
USER 65532:65532

ENTRYPOINT ["/terraform-controller"]
