// generated by 'threeport-codegen controller' - do not edit

package radiusworkload

// The name and description of the NATS bucket used for radius workload object locks
const (
	LockBucketName  = "radiusWorkloadLock"
	LockBucketDescr = "contains locks on radius workload objects"
)
