name: Clone

on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-22.04
    steps:

      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Clone release
        uses: andrewthetechie/gha-clone-releases@v1.7.0
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          src_repo: threeport/threeport
          dest_repo: threeport/releases
          copy_assets: true

