name: Docs

on:
  push:
    tags:
      - 'docs*'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/setup-python@v4.6.1
      with:
        python-version: 3.x
    - run: pip install mkdocs-material mkdocs-material-extensions mike
    - run: cd docs && mkdocs gh-deploy --force

