name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    uses: ./.github/workflows/_goreleaser.yml

  images:
    needs: goreleaser
    uses: ./.github/workflows/_build-images.yml
    with:
      tag: ${{ github.ref_name }}
      image_repo: ghcr.io/threeport
    secrets: inherit
