name: Test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install mage
      run: go install github.com/magefile/mage@latest

    - name: Install threeport-sdk
      run: mage install:sdk

    - name: Run threeport-sdk
      run: $(go env GOPATH)/bin/threeport-sdk gen --config sdk-config.yaml

    - name: Ensure no changes were made by threeport-sdk
      run: git diff --exit-code

    - name: Create local container registry
      run: mage dev:localRegistryUp

    - name: Build and push control plane component images
      run: mage build:allImagesDev

    - name: Build tptctl
      run: mage build:tptctl

    - name: Create test control plane
      run: mage test:up

    - name: Run tests
      run: mage test:integration
