// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	errors "errors"
	"fmt"
	"net/http"

	"gopkg.in/ini.v1"

	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	"github.com/threeport/threeport/pkg/encryption/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// AwsAccountConfig is a config abstraction for the AwsAccount API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type AwsAccountConfig struct {
	AwsAccount AwsAccountValues `yaml:"AwsAccount"`
}

// AwsAccountValues contains all the attributes needed to manage
// the AwsAccount API object.
type AwsAccountValues struct {
	Name             *string `json:"Name,omitempty" yaml:"Name,omitempty"`
	AccountID        *string `json:"AccountID,omitempty" yaml:"AccountID,omitempty"`
	DefaultAccount   *bool   `json:"DefaultAccount,omitempty" yaml:"DefaultAccount,omitempty"`
	DefaultRegion    *string `json:"DefaultRegion,omitempty" yaml:"DefaultRegion,omitempty"`
	AccessKeyID      *string `json:"AccessKeyID,omitempty" yaml:"AccessKeyID,omitempty"`
	SecretAccessKey  *string `json:"SecretAccessKey,omitempty" yaml:"SecretAccessKey,omitempty"`
	RoleArn          *string `json:"RoleArn,omitempty" yaml:"RoleArn,omitempty"`
	LocalConfig      *string `json:"LocalConfig,omitempty" yaml:"LocalConfig,omitempty"`
	LocalCredentials *string `json:"LocalCredentials,omitempty" yaml:"LocalCredentials,omitempty"`
	LocalProfile     *string `json:"LocalProfile,omitempty" yaml:"LocalProfile,omitempty"`
	Age              *string `json:"Age,omitempty" yaml:"Age,omitempty"`
}

// Get gets aws accounts from the Threeport API.
// If the name is set in the AwsAccountValues, it will return the aws account with that name.
// If the name is not set, it will return all aws accounts.
// If the encryptionKey is provided, it will decrypt the SecretAccessKey and AccessKeyID fields.
func (a *AwsAccountConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
	encryptionKey string,
) (*[]AwsAccountConfig, error) {
	awsAccountValues := a.AwsAccount
	// get API objects
	var awsAccounts *[]api_v0.AwsAccount
	switch {
	// if name is provided, get aws account by name
	case awsAccountValues.Name != nil:
		awsAccount, err := client_v0.GetAwsAccountByName(apiClient, apiEndpoint, *awsAccountValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get aws account with name %s: %w", *awsAccountValues.Name, err)
		}
		awsAccounts = &[]api_v0.AwsAccount{*awsAccount}
	// get all aws accounts
	default:
		allAwsAccounts, err := client_v0.GetAwsAccounts(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get aws accounts from Threeport API: %w", err)
		}
		awsAccounts = allAwsAccounts
	}

	// assemble config objects from API objects
	var awsAccountConfigs []AwsAccountConfig
	for _, awsAccount := range *awsAccounts {
		// handle encryption if needed
		if encryptionKey != "" {
			a, err := encryption.DecryptValues(&awsAccount, encryptionKey)
			if err != nil {
				return nil, fmt.Errorf("failed to decrypt aws account secret values: %w", err)
			}
			awsAccount = *(a.(*api_v0.AwsAccount))
		} else {
			a := encryption.RedactEncryptedValues(&awsAccount)
			awsAccount = *(a.(*api_v0.AwsAccount))
		}

		awsAccountConfig := AwsAccountConfig{
			AwsAccount: AwsAccountValues{
				Name:            awsAccount.Name,
				AccountID:       awsAccount.AccountID,
				DefaultAccount:  awsAccount.DefaultAccount,
				DefaultRegion:   awsAccount.DefaultRegion,
				RoleArn:         awsAccount.RoleArn,
				AccessKeyID:     awsAccount.AccessKeyID,
				SecretAccessKey: awsAccount.SecretAccessKey,
				Age:             util.Ptr(util.GetAgeFormatted(awsAccount.CreatedAt)),
			},
		}
		awsAccountConfigs = append(awsAccountConfigs, awsAccountConfig)
	}

	return &awsAccountConfigs, nil
}

// Create creates a aws account in the Threeport API.
func (a *AwsAccountConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*AwsAccountConfig, error) {
	awsAccountValues := a.AwsAccount

	// validate config
	if err := a.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for aws account with name %s: %w", *awsAccountValues.Name, err)
	}

	// validate that no other default AWS account exists
	if awsAccountValues.DefaultAccount != nil && *awsAccountValues.DefaultAccount {
		existingAccounts, err := client_v0.GetAwsAccounts(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to retrieve existing AWS accounts to check default accounts: %w", err)
		}
		for _, existing := range *existingAccounts {
			if existing.DefaultAccount != nil && *existing.DefaultAccount {
				msg := fmt.Sprintf("cannot designate new account as default account - %s is already the default account", *existing.Name)
				return nil, errors.New(msg)
			}
		}
	}

	// establish default region from explicit declaration in config or AWS config file
	var region string
	if awsAccountValues.DefaultRegion == nil {
		awsConfig, err := ini.Load(*awsAccountValues.LocalConfig)
		if err != nil {
			return nil, fmt.Errorf("failed to load aws config: %w", err)
		}
		if awsConfig.Section(*awsAccountValues.LocalProfile).HasKey("region") {
			region = awsConfig.Section(*awsAccountValues.LocalProfile).Key("region").String()
		} else {
			return nil, fmt.Errorf(
				"profile %s not found in aws config %s",
				*awsAccountValues.LocalProfile,
				*awsAccountValues.LocalConfig,
			)
		}
	} else {
		region = *awsAccountValues.DefaultRegion
	}

	// retrieve access key ID and secret access key if needed
	var accessKeyID string
	var secretAccessKey string
	if awsAccountValues.AccessKeyID == nil && awsAccountValues.SecretAccessKey == nil {
		awsCredentials, err := ini.Load(*awsAccountValues.LocalCredentials)
		if err != nil {
			return nil, fmt.Errorf("failed to load aws credentials: %w", err)
		}
		if awsCredentials.Section(*awsAccountValues.LocalProfile).HasKey("aws_access_key_id") &&
			awsCredentials.Section(*awsAccountValues.LocalProfile).HasKey("aws_secret_access_key") {
			accessKeyID = awsCredentials.Section(*awsAccountValues.LocalProfile).Key("aws_access_key_id").String()
			secretAccessKey = awsCredentials.Section(*awsAccountValues.LocalProfile).Key("aws_secret_access_key").String()
		}
	} else {
		accessKeyID = *awsAccountValues.AccessKeyID
		secretAccessKey = *awsAccountValues.SecretAccessKey
	}

	// construct aws account object
	awsAccount := api_v0.AwsAccount{
		Name:            awsAccountValues.Name,
		DefaultAccount:  awsAccountValues.DefaultAccount,
		DefaultRegion:   &region,
		AccountID:       awsAccountValues.AccountID,
		AccessKeyID:     &accessKeyID,
		SecretAccessKey: &secretAccessKey,
		RoleArn:         awsAccountValues.RoleArn,
	}

	// create aws account
	createdAwsAccount, err := client_v0.CreateAwsAccount(
		apiClient,
		apiEndpoint,
		&awsAccount,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create aws account in threeport API: %w", err)
	}

	// construct aws account config
	createdAwsAccountConfig := &AwsAccountConfig{
		AwsAccount: AwsAccountValues{
			Age:            util.Ptr(util.GetAgeFormatted(createdAwsAccount.CreatedAt)),
			Name:           createdAwsAccount.Name,
			AccountID:      createdAwsAccount.AccountID,
			DefaultAccount: createdAwsAccount.DefaultAccount,
			DefaultRegion:  createdAwsAccount.DefaultRegion,
			RoleArn:        createdAwsAccount.RoleArn,
		},
	}

	return createdAwsAccountConfig, nil
}

// Replace updates the entire aws account object in the Threeport API.
// This is a full replacement of all fields in the aws account object.
// This function takes a name parameter to identify the aws account to replace.
// This allows a different name to be provided in the values object for name changes.
func (a *AwsAccountConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*AwsAccountConfig, error) {
	awsAccountValues := a.AwsAccount

	// validate config
	if err := a.Validate(); err != nil {
		return nil, fmt.Errorf("invalid aws account config: %w", err)
	}

	// get existing aws account by name
	existingAwsAccount, err := client_v0.GetAwsAccountByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find aws account with name %s: %w", name, err)
	}

	// construct updated aws account object
	updatedAwsAccount := &api_v0.AwsAccount{
		Common: api_v0.Common{
			ID: existingAwsAccount.ID,
		},
		Name:            awsAccountValues.Name,
		AccountID:       awsAccountValues.AccountID,
		DefaultAccount:  awsAccountValues.DefaultAccount,
		DefaultRegion:   awsAccountValues.DefaultRegion,
		AccessKeyID:     awsAccountValues.AccessKeyID,
		SecretAccessKey: awsAccountValues.SecretAccessKey,
		RoleArn:         awsAccountValues.RoleArn,
	}

	// replace aws account
	replacedAwsAccount, err := client_v0.ReplaceAwsAccount(
		apiClient,
		apiEndpoint,
		updatedAwsAccount,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace aws account in threeport API: %w", err)
	}

	// construct updated aws account config
	updatedAwsAccountConfig := &AwsAccountConfig{
		AwsAccount: AwsAccountValues{
			Age:            util.Ptr(util.GetAgeFormatted(replacedAwsAccount.CreatedAt)),
			Name:           replacedAwsAccount.Name,
			AccountID:      replacedAwsAccount.AccountID,
			DefaultAccount: replacedAwsAccount.DefaultAccount,
			DefaultRegion:  replacedAwsAccount.DefaultRegion,
			RoleArn:        replacedAwsAccount.RoleArn,
		},
	}

	return updatedAwsAccountConfig, nil
}

// Delete deletes a aws account from the Threeport API.
func (a *AwsAccountConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*AwsAccountConfig, error) {
	awsAccountValues := a.AwsAccount

	// get aws account by name
	awsAccount, err := client_v0.GetAwsAccountByName(
		apiClient,
		apiEndpoint,
		*awsAccountValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find aws account with name %s: %w", *awsAccountValues.Name, err)
	}

	// delete aws account
	deletedAwsAccount, err := client_v0.DeleteAwsAccount(
		apiClient,
		apiEndpoint,
		*awsAccount.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete aws account from Threeport API: %w", err)
	}

	// construct deleted aws account config
	deletedAwsAccountConfig := &AwsAccountConfig{
		AwsAccount: AwsAccountValues{
			Name:           deletedAwsAccount.Name,
			AccountID:      deletedAwsAccount.AccountID,
			DefaultAccount: deletedAwsAccount.DefaultAccount,
			DefaultRegion:  deletedAwsAccount.DefaultRegion,
			RoleArn:        deletedAwsAccount.RoleArn,
		},
	}

	return deletedAwsAccountConfig, nil
}

// Validate validates inputs to create aws accounts.
func (a *AwsAccountConfig) Validate() error {
	awsAccountValues := a.AwsAccount
	multiError := util.MultiError{}

	// ensure name is set
	if awsAccountValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// ensure account ID is set
	if awsAccountValues.AccountID == nil {
		multiError.AppendError(errors.New("missing required field in config: AccountID"))
	}

	// validate config and credentials properly provided
	explain := `
In order to configure an AWS account provide the fields:
DefaultRegion, AccessKeyID and SecretAccessKey
OR
LocalConfig, LocalCredentials and LocalProfile
`
	localConfig := false
	explicitConfig := false
	if awsAccountValues.LocalConfig != nil && awsAccountValues.LocalCredentials != nil && awsAccountValues.LocalProfile != nil {
		localConfig = true
	}
	if awsAccountValues.DefaultRegion != nil && awsAccountValues.AccessKeyID != nil && awsAccountValues.SecretAccessKey != nil {
		explicitConfig = true
	}
	switch {
	case localConfig && explicitConfig:
		msg := fmt.Sprintf("local and explicit configurations provided %s", explain)
		multiError.AppendError(errors.New(msg))
	case !localConfig && !explicitConfig:
		msg := fmt.Sprintf("neither local nor explicit configurations provided %s", explain)
		multiError.AppendError(errors.New(msg))
	}

	return multiError.Error()
}
