// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"errors"
	"fmt"
	"net/http"

	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// GatewayInstanceConfig is a config abstraction for the GatewayInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type GatewayInstanceConfig struct {
	GatewayInstance GatewayInstanceValues
}

// GatewayInstanceValues contains all the attributes needed to manage
// the GatewayInstance API object.
type GatewayInstanceValues struct {
	Name                       *string                           `json:",omitempty"`
	GatewayDefinition          *GatewayDefinitionValues          `json:",omitempty"`
	KubernetesRuntimeInstance  *KubernetesRuntimeInstanceValues  `json:",omitempty"`
	KubernetesWorkloadInstance *KubernetesWorkloadInstanceValues `json:",omitempty"`
	Age                        *string                           `json:",omitempty"`
}

// Get gets gateway instances from the Threeport API.
// If the name is set in the GatewayInstanceValues, it will return the gateway instance with that name.
// If the name is not set, it will return all gateway instances.
func (g *GatewayInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]GatewayInstanceConfig, error) {
	gatewayInstanceValues := g.GatewayInstance
	// get API objects
	var gatewayInstances *[]api_v0.GatewayInstance
	switch {
	// if name is provided, get gateway instance by name
	case gatewayInstanceValues.Name != nil:
		gatewayInstance, err := client_v0.GetGatewayInstanceByName(apiClient, apiEndpoint, *gatewayInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get gateway instance with name %s: %w", *gatewayInstanceValues.Name, err)
		}
		gatewayInstances = &[]api_v0.GatewayInstance{*gatewayInstance}
	// get all gateway instances
	default:
		allGatewayInstances, err := client_v0.GetGatewayInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get gateway instances from Threeport API: %w", err)
		}
		gatewayInstances = allGatewayInstances
	}

	// assemble config objects from API objects
	var gatewayInstanceConfigs []GatewayInstanceConfig
	for _, gatewayInstance := range *gatewayInstances {
		// related objects
		var gatewayDefinition *GatewayDefinitionValues
		var kubernetesRuntimeInstance *KubernetesRuntimeInstanceValues
		var workloadInstance *KubernetesWorkloadInstanceValues

		// get gateway definition
		if gatewayInstance.GatewayDefinitionID != nil {
			gd, err := client_v0.GetGatewayDefinitionByID(apiClient, apiEndpoint, *gatewayInstance.GatewayDefinitionID)
			if err == nil {
				gatewayDefinition = &GatewayDefinitionValues{
					Name: gd.Name,
				}
			}
		}

		// get kubernetes runtime instance
		if gatewayInstance.KubernetesRuntimeInstanceID != nil {
			kri, err := client_v0.GetKubernetesRuntimeInstanceByID(apiClient, apiEndpoint, *gatewayInstance.KubernetesRuntimeInstanceID)
			if err == nil {
				kubernetesRuntimeInstance = &KubernetesRuntimeInstanceValues{
					Name: kri.Name,
				}
			}
		}

		// get kubernetes workload instance
		if gatewayInstance.KubernetesWorkloadInstanceID != nil {
			wi, err := client_v0.GetKubernetesWorkloadInstanceByID(apiClient, apiEndpoint, *gatewayInstance.KubernetesWorkloadInstanceID)
			if err == nil {
				workloadInstance = &KubernetesWorkloadInstanceValues{
					Name: wi.Name,
				}
			}
		}

		gatewayInstanceConfig := GatewayInstanceConfig{
			GatewayInstance: GatewayInstanceValues{
				Name:                       gatewayInstance.Name,
				GatewayDefinition:          gatewayDefinition,
				KubernetesRuntimeInstance:  kubernetesRuntimeInstance,
				KubernetesWorkloadInstance: workloadInstance,
				Age:                        util.Ptr(util.GetAgeFormatted(gatewayInstance.CreatedAt)),
			},
		}
		gatewayInstanceConfigs = append(gatewayInstanceConfigs, gatewayInstanceConfig)
	}

	return &gatewayInstanceConfigs, nil
}

// Create creates a gateway instance in the Threeport API.
func (g *GatewayInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*GatewayInstanceConfig, error) {
	gatewayInstanceValues := g.GatewayInstance

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for gateway instance with name %s: %w", *gatewayInstanceValues.Name, err)
	}

	// get kubernetes runtime instance
	kubernetesRuntimeInstance, err := getKubernetesRuntimeInstanceByNameOrDefault(
		apiClient,
		apiEndpoint,
		gatewayInstanceValues.KubernetesRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}

	// get kubernetes workload instance
	workloadInstance, err := client_v0.GetKubernetesWorkloadInstanceByName(apiClient, apiEndpoint, *gatewayInstanceValues.KubernetesWorkloadInstance.Name)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes workload instance with name %s: %w", *gatewayInstanceValues.KubernetesWorkloadInstance.Name, err)
	}

	// get gateway definition
	gatewayDefinition, err := client_v0.GetGatewayDefinitionByName(apiClient, apiEndpoint, *gatewayInstanceValues.GatewayDefinition.Name)
	if err != nil {
		return nil, fmt.Errorf("failed to get gateway definition with name %s: %w", *gatewayInstanceValues.GatewayDefinition.Name, err)
	}

	// construct gateway instance object
	gatewayInstance := api_v0.GatewayInstance{
		Instance: api_v0.Instance{
			Name: gatewayInstanceValues.Name,
		},
		GatewayDefinitionID:          gatewayDefinition.ID,
		KubernetesRuntimeInstanceID:  kubernetesRuntimeInstance.ID,
		KubernetesWorkloadInstanceID: workloadInstance.ID,
	}

	// create gateway instance
	createdGatewayInstance, err := client_v0.CreateGatewayInstance(
		apiClient,
		apiEndpoint,
		&gatewayInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create gateway instance in threeport API: %w", err)
	}

	// construct gateway instance config
	createdGatewayInstanceConfig := &GatewayInstanceConfig{
		GatewayInstance: GatewayInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(createdGatewayInstance.CreatedAt)),
			Name: createdGatewayInstance.Name,
		},
	}

	return createdGatewayInstanceConfig, nil
}

// Replace updates the entire gateway instance object in the Threeport API.
// This is a full replacement of all fields in the gateway instance object.
// This function takes a name parameter to identify the gateway instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (g *GatewayInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*GatewayInstanceConfig, error) {
	gatewayInstanceValues := g.GatewayInstance

	// validate config
	if err := g.Validate(); err != nil {
		return nil, fmt.Errorf("invalid gateway instance config: %w", err)
	}

	// get existing gateway instance by name
	existingGatewayInstance, err := client_v0.GetGatewayInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gateway instance with name %s: %w", name, err)
	}

	// ensure user is not trying to move the gateway to a different runtime
	kubernetesRuntimeInstance, moved, err := getKubernetesRuntimeInstanceAndCheckId(
		apiClient,
		apiEndpoint,
		gatewayInstanceValues.KubernetesRuntimeInstance,
		existingGatewayInstance.KubernetesRuntimeInstanceID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}
	if moved {
		return nil, fmt.Errorf(
			"a gateway may not be moved from its current runtime to %s - if %[1]s runtime needs this gateway, create a new instance there instead",
			*kubernetesRuntimeInstance.Name,
		)
	}

	// get kubernetes workload instance for update
	workloadInstance, err := client_v0.GetKubernetesWorkloadInstanceByName(apiClient, apiEndpoint, *gatewayInstanceValues.KubernetesWorkloadInstance.Name)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes workload instance with name %s: %w", *gatewayInstanceValues.KubernetesWorkloadInstance.Name, err)
	}

	// get gateway definition for update
	gatewayDefinition, err := client_v0.GetGatewayDefinitionByName(apiClient, apiEndpoint, *gatewayInstanceValues.GatewayDefinition.Name)
	if err != nil {
		return nil, fmt.Errorf("failed to get gateway definition with name %s: %w", *gatewayInstanceValues.GatewayDefinition.Name, err)
	}

	// construct updated gateway instance object
	updatedGatewayInstance := &api_v0.GatewayInstance{
		Common: api_v0.Common{
			ID: existingGatewayInstance.ID,
		},
		Instance: api_v0.Instance{
			Name: gatewayInstanceValues.Name,
		},
		GatewayDefinitionID:          gatewayDefinition.ID,
		KubernetesRuntimeInstanceID:  kubernetesRuntimeInstance.ID,
		KubernetesWorkloadInstanceID: workloadInstance.ID,
	}

	// replace gateway instance
	replacedGatewayInstance, err := client_v0.ReplaceGatewayInstance(
		apiClient,
		apiEndpoint,
		updatedGatewayInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace gateway instance in threeport API: %w", err)
	}

	// construct updated gateway instance config
	updatedGatewayInstanceConfig := &GatewayInstanceConfig{
		GatewayInstance: GatewayInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(replacedGatewayInstance.CreatedAt)),
			Name: replacedGatewayInstance.Name,
		},
	}

	return updatedGatewayInstanceConfig, nil
}

// Delete deletes a gateway instance from the Threeport API.
func (g *GatewayInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*GatewayInstanceConfig, error) {
	gatewayInstanceValues := g.GatewayInstance

	// get gateway instance by name
	gatewayInstance, err := client_v0.GetGatewayInstanceByName(
		apiClient,
		apiEndpoint,
		*gatewayInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find gateway instance with name %s: %w", *gatewayInstanceValues.Name, err)
	}

	// delete gateway instance
	deletedGatewayInstance, err := client_v0.DeleteGatewayInstance(
		apiClient,
		apiEndpoint,
		*gatewayInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete gateway instance from Threeport API: %w", err)
	}

	// wait for gateway instance to be deleted
	util.Retry(60, 1, func() error {
		if _, err := client_v0.GetGatewayInstanceByName(apiClient, apiEndpoint, *gatewayInstanceValues.Name); err == nil {
			return errors.New("gateway instance not deleted")
		}
		return nil
	})

	// construct deleted gateway instance config
	deletedGatewayInstanceConfig := &GatewayInstanceConfig{
		GatewayInstance: GatewayInstanceValues{
			Name: deletedGatewayInstance.Name,
		},
	}

	return deletedGatewayInstanceConfig, nil
}

// Validate validates inputs to create gateway instances.
func (g *GatewayInstanceConfig) Validate() error {
	gatewayInstanceValues := g.GatewayInstance
	multiError := util.MultiError{}

	if gatewayInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	if gatewayInstanceValues.GatewayDefinition == nil || gatewayInstanceValues.GatewayDefinition.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: GatewayDefinition.Name"))
	}

	if gatewayInstanceValues.KubernetesWorkloadInstance == nil || gatewayInstanceValues.KubernetesWorkloadInstance.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: KubernetesWorkloadInstance.Name"))
	}

	if len(multiError.Errors) > 0 {
		return multiError.Error()
	}

	return nil
}
