// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	"net/http"

	util "github.com/threeport/threeport/pkg/util/v0"
)

// MachineWorkloadConfig is a container for a MachineWorkload which is a config abstraction for
// the MachineWorkloadDefinition and MachineWorkloadInstance API objects.
// This abstraction allows users to manage definitions and instances together with single operations
// rather than separate operations for each API object.
type MachineWorkloadConfig struct {
	MachineWorkload MachineWorkloadValues
}

// MachineWorkloadValues contains all the attributes needed to manage the
// MachineWorkloadDefinition and MachineWorkloadInstance API objects
// together with a single operation.
type MachineWorkloadValues struct {
	Name                   *string  `json:",omitempty"`
	CreateScript           *string  `json:",omitempty"`
	UpdateScript           *string  `json:",omitempty"`
	DeleteScript           *string  `json:",omitempty"`
	Shell                  *string  `json:",omitempty"`
	WorkingDir             *string  `json:",omitempty"`
	Timeout                *int     `json:",omitempty"`
	Env                    []string `json:",omitempty"`
	MachineRuntimeInstance *string  `json:",omitempty"`
	Status                 *string  `json:",omitempty"`
	Age                    *string  `json:",omitempty"`
}

// Get gets a machine workload definition and instance from the Threeport API.
func (m *MachineWorkloadConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
	encryptionKey string,
) (*[]MachineWorkloadConfig, error) {
	// get operations
	operations, machineWorkloadDefinitions, machineWorkloadInstances := m.GetOperations(
		apiClient,
		apiEndpoint,
		encryptionKey,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for machine workload defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	machineWorkloadConfigs := mapToMachineWorkloadDefinedInstances(machineWorkloadDefinitions, machineWorkloadInstances)

	return machineWorkloadConfigs, nil
}

// Create creates a machine workload definition and instance in the Threeport API.
func (m *MachineWorkloadConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]MachineWorkloadConfig, error) {
	// get operations
	operations, machineWorkloadDefinitions, machineWorkloadInstances := m.GetOperations(
		apiClient,
		apiEndpoint,
		"",
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for machine workload defined instance with name %s: %w",
			*m.MachineWorkload.Name,
			err,
		)
	}

	// assemble the defined instances
	machineWorkloadConfigs := mapToMachineWorkloadDefinedInstances(machineWorkloadDefinitions, machineWorkloadInstances)

	return machineWorkloadConfigs, nil
}

// Replace replaces a machine workload definition and instance in the Threeport API.
func (m *MachineWorkloadConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]MachineWorkloadConfig, error) {
	// get operations
	operations, machineWorkloadDefinitions, machineWorkloadInstances := m.GetOperations(
		apiClient,
		apiEndpoint,
		"",
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for machine workload defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	machineWorkloadConfigs := mapToMachineWorkloadDefinedInstances(machineWorkloadDefinitions, machineWorkloadInstances)

	return machineWorkloadConfigs, nil
}

// Delete deletes a machine workload definition and instance from the Threeport API.
func (m *MachineWorkloadConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]MachineWorkloadConfig, error) {
	// get operations
	operations, _, _ := m.GetOperations(
		apiClient,
		apiEndpoint,
		"",
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for machine workload defined instance with name %s: %w",
			*m.MachineWorkload.Name,
			err,
		)
	}

	return nil, nil
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a machine workload defined instance.
func (m *MachineWorkloadConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
	encryptionKey string,
) (*util.Operations, *[]MachineWorkloadDefinitionConfig, *[]MachineWorkloadInstanceConfig) {
	machineWorkloadValues := m.MachineWorkload
	var err error
	var operatedMachineWorkloadDefinitions []MachineWorkloadDefinitionConfig
	var operatedMachineWorkloadInstances []MachineWorkloadInstanceConfig

	operations := util.Operations{}

	// add machine workload definition operation
	machineWorkloadDefinitionConfig := MachineWorkloadDefinitionConfig{
		MachineWorkloadDefinition: MachineWorkloadDefinitionValues{
			Name:         machineWorkloadValues.Name,
			CreateScript: machineWorkloadValues.CreateScript,
			UpdateScript: machineWorkloadValues.UpdateScript,
			DeleteScript: machineWorkloadValues.DeleteScript,
			Shell:        machineWorkloadValues.Shell,
			WorkingDir:   machineWorkloadValues.WorkingDir,
			Timeout:      machineWorkloadValues.Timeout,
			Env:          machineWorkloadValues.Env,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			machineWorkloadDefinition, err := machineWorkloadDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create machine workload definition with name %s: %w", *machineWorkloadValues.Name, err)
			}
			operatedMachineWorkloadDefinitions = append(operatedMachineWorkloadDefinitions, *machineWorkloadDefinition)
			return nil
		},
		Delete: func() error {
			_, err = machineWorkloadDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete machine workload definition with name %s: %w", *machineWorkloadValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			machineWorkloadDefinitions, err := machineWorkloadDefinitionConfig.Get(apiClient, apiEndpoint, encryptionKey)
			if err != nil {
				return fmt.Errorf("failed to get machine workload definitions: %w", err)
			}
			operatedMachineWorkloadDefinitions = append(operatedMachineWorkloadDefinitions, *machineWorkloadDefinitions...)
			return nil
		},
		Name: "machine workload definition",
		Replace: func(name string) error {
			machineWorkloadDefinition, err := machineWorkloadDefinitionConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace machine workload definition with name %s: %w", name, err)
			}
			operatedMachineWorkloadDefinitions = append(operatedMachineWorkloadDefinitions, *machineWorkloadDefinition)
			return nil
		},
	})

	// add machine workload instance operation
	machineWorkloadInstanceConfig := MachineWorkloadInstanceConfig{
		MachineWorkloadInstance: MachineWorkloadInstanceValues{
			Name: machineWorkloadValues.Name,
			MachineWorkloadDefinition: &MachineWorkloadDefinitionValues{
				Name: machineWorkloadValues.Name,
			},
			MachineRuntimeInstance: &MachineRuntimeInstanceValues{
				Name: machineWorkloadValues.MachineRuntimeInstance,
			},
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			machineWorkloadInstance, err := machineWorkloadInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create machine workload instance with name %s: %w", *machineWorkloadValues.Name, err)
			}
			operatedMachineWorkloadInstances = append(operatedMachineWorkloadInstances, *machineWorkloadInstance)
			return nil
		},
		Delete: func() error {
			_, err = machineWorkloadInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete machine workload instance with name %s: %w", *machineWorkloadValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			machineWorkloadInstances, err := machineWorkloadInstanceConfig.Get(apiClient, apiEndpoint, encryptionKey)
			if err != nil {
				return fmt.Errorf("failed to get machine workload instances: %w", err)
			}
			operatedMachineWorkloadInstances = append(operatedMachineWorkloadInstances, *machineWorkloadInstances...)
			return nil
		},
		Name: "machine workload instance",
		Replace: func(name string) error {
			machineWorkloadInstance, err := machineWorkloadInstanceConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace machine workload instance with name %s: %w", name, err)
			}
			operatedMachineWorkloadInstances = append(operatedMachineWorkloadInstances, *machineWorkloadInstance)
			return nil
		},
	})

	return &operations, &operatedMachineWorkloadDefinitions, &operatedMachineWorkloadInstances
}

// mapToMachineWorkloadDefinedInstances maps a slice of machine workload definition and instance configs
// to a slice of machine workload config objects
func mapToMachineWorkloadDefinedInstances(
	machineWorkloadDefinitions *[]MachineWorkloadDefinitionConfig,
	machineWorkloadInstances *[]MachineWorkloadInstanceConfig,
) *[]MachineWorkloadConfig {
	var machineWorkloadConfigs []MachineWorkloadConfig
	for _, inst := range *machineWorkloadInstances {
		for _, def := range *machineWorkloadDefinitions {
			instName := *inst.MachineWorkloadInstance.Name
			defName := *def.MachineWorkloadDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && *inst.MachineWorkloadInstance.MachineWorkloadDefinition.Name == *def.MachineWorkloadDefinition.Name {
				var machineRuntimeInstanceName *string
				if inst.MachineWorkloadInstance.MachineRuntimeInstance != nil {
					machineRuntimeInstanceName = inst.MachineWorkloadInstance.MachineRuntimeInstance.Name
				}
				machineWorkloadConfig := MachineWorkloadConfig{
					MachineWorkload: MachineWorkloadValues{
						Name:                   inst.MachineWorkloadInstance.Name,
						CreateScript:           def.MachineWorkloadDefinition.CreateScript,
						UpdateScript:           def.MachineWorkloadDefinition.UpdateScript,
						DeleteScript:           def.MachineWorkloadDefinition.DeleteScript,
						Shell:                  def.MachineWorkloadDefinition.Shell,
						WorkingDir:             def.MachineWorkloadDefinition.WorkingDir,
						Timeout:                def.MachineWorkloadDefinition.Timeout,
						Env:                    def.MachineWorkloadDefinition.Env,
						MachineRuntimeInstance: machineRuntimeInstanceName,
						Status:                 inst.MachineWorkloadInstance.Status,
						Age:                    inst.MachineWorkloadInstance.Age,
					},
				}
				machineWorkloadConfigs = append(machineWorkloadConfigs, machineWorkloadConfig)
				break
			}
		}
	}

	return &machineWorkloadConfigs
}
