// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"errors"
	"fmt"
	"net/http"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/threeport/threeport/internal/agent"
	"github.com/threeport/threeport/internal/workload/status"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	kube "github.com/threeport/threeport/pkg/kube/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// WorkloadInstanceConfig is a config abstraction for the WorkloadInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type WorkloadInstanceConfig struct {
	WorkloadInstance WorkloadInstanceValues `yaml:"WorkloadInstance"`
}

// WorkloadInstanceValues contains all the attributes needed to manage
// the WorkloadInstance API object.
type WorkloadInstanceValues struct {
	Name                      *string                          `json:"Name,omitempty" yaml:"Name,omitempty"`
	KubernetesRuntimeInstance *KubernetesRuntimeInstanceValues `json:"KubernetesRuntimeInstance,omitempty" yaml:"KubernetesRuntimeInstance,omitempty"`
	WorkloadDefinition        *WorkloadDefinitionValues        `json:"WorkloadDefinition,omitempty" yaml:"WorkloadDefinition,omitempty"`
	Status                    *string                          `json:"Status,omitempty" yaml:"Status,omitempty"`
	Age                       *string                          `json:"Age,omitempty" yaml:"Age,omitempty"`
}

// Get gets workload instances from the Threeport API.
// If the name is set in the WorkloadInstanceValues, it will return the workload instance with that name.
// If the name is not set, it will return all workload instances.
func (w *WorkloadInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]WorkloadInstanceConfig, error) {
	workloadInstanceValues := w.WorkloadInstance
	// get API objects
	var workloadInstances *[]api_v0.WorkloadInstance
	switch {
	// if name is provided, get workload instance by name
	case workloadInstanceValues.Name != nil:
		workloadInstance, err := client_v0.GetWorkloadInstanceByName(apiClient, apiEndpoint, *workloadInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get workload instance with name %s: %w", *workloadInstanceValues.Name, err)
		}
		workloadInstances = &[]api_v0.WorkloadInstance{*workloadInstance}
	// get all workload instances
	default:
		allWorkloadInstances, err := client_v0.GetWorkloadInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get workload instances from Threeport API: %w", err)
		}
		workloadInstances = allWorkloadInstances
	}

	// assemble config objects from API objects
	var workloadInstanceConfigs []WorkloadInstanceConfig
	for _, workloadInstance := range *workloadInstances {
		// related objects
		var kubernetesRuntimeInstance *KubernetesRuntimeInstanceValues
		var workloadDefinition *WorkloadDefinitionValues

		// get kubernetes runtime instance
		if workloadInstance.KubernetesRuntimeInstanceID != nil {
			kri, err := client_v0.GetKubernetesRuntimeInstanceByID(apiClient, apiEndpoint, *workloadInstance.KubernetesRuntimeInstanceID)
			if err == nil {
				kubernetesRuntimeInstance = &KubernetesRuntimeInstanceValues{
					Name: kri.Name,
				}
			}
		}

		// get workload definition
		if workloadInstance.WorkloadDefinitionID != nil {
			wd, err := client_v0.GetWorkloadDefinitionByID(apiClient, apiEndpoint, *workloadInstance.WorkloadDefinitionID)
			if err == nil {
				workloadDefinition = &WorkloadDefinitionValues{
					Name: wd.Name,
				}
			}
		}

		// determine the workload instance status
		instanceStatusDetail := status.GetWorkloadInstanceStatus(
			apiClient,
			apiEndpoint,
			agent.WorkloadInstanceType,
			*workloadInstance.ID,
			*workloadInstance.Reconciled,
		)
		if instanceStatusDetail.Error != nil {
			return nil, fmt.Errorf("failed to get workload instance status: %w", instanceStatusDetail.Error)
		}

		workloadInstanceConfig := WorkloadInstanceConfig{
			WorkloadInstance: WorkloadInstanceValues{
				Name:                      workloadInstance.Name,
				KubernetesRuntimeInstance: kubernetesRuntimeInstance,
				WorkloadDefinition:        workloadDefinition,
				Status:                    util.Ptr(string(instanceStatusDetail.Status)),
				Age:                       util.Ptr(util.GetAgeFormatted(workloadInstance.CreatedAt)),
			},
		}
		workloadInstanceConfigs = append(workloadInstanceConfigs, workloadInstanceConfig)
	}

	return &workloadInstanceConfigs, nil
}

// Create creates a workload instance in the Threeport API.
func (w *WorkloadInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*WorkloadInstanceConfig, error) {
	workloadInstanceValues := w.WorkloadInstance
	// validate config
	if err := w.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for workload instance with name %s: %w", *workloadInstanceValues.Name, err)
	}

	// get kubernetes runtime instance
	kubernetesRuntimeInstance, err := getKubernetesRuntimeInstanceByNameOrDefault(
		apiClient,
		apiEndpoint,
		workloadInstanceValues.KubernetesRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}

	// get workload definition by name
	workloadDefinition, err := client_v0.GetWorkloadDefinitionByName(
		apiClient,
		apiEndpoint,
		*workloadInstanceValues.WorkloadDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get workload definition by name %s: %w", *workloadInstanceValues.WorkloadDefinition.Name, err)
	}

	// check to see if threeport is managing namespace
	jsonObjects, err := kube.GetJsonResourcesFromYamlDoc(*workloadDefinition.YAMLDocument)
	if err != nil {
		return nil, fmt.Errorf("failed to get json resources from yaml document: %w", err)
	}
	threeportManagedNs := true
	for _, jsonContent := range jsonObjects {
		kubeObject := &unstructured.Unstructured{Object: map[string]interface{}{}}
		if err := kubeObject.UnmarshalJSON(jsonContent); err != nil {
			return nil, fmt.Errorf("failed to unmarshal json to kubernetes unstructured object: %w", err)
		}
		if kubeObject.GetKind() == "Namespace" {
			threeportManagedNs = false
		}
	}

	if !threeportManagedNs {
		// if client managed namespaces, get instances for definition
		instances, err := client_v0.GetWorkloadInstancesByWorkloadDefinitionID(
			apiClient,
			apiEndpoint,
			*workloadDefinition.ID,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to get workload instances by workload definition ID %d: %w", *workloadDefinition.ID, err)
		}

		// if there's already an instance for a workload with client managed
		// namespace, check clusters
		var runtimeNames []string
		for _, inst := range *instances {
			runtime, err := client_v0.GetKubernetesRuntimeInstanceByID(
				apiClient,
				apiEndpoint,
				*inst.KubernetesRuntimeInstanceID,
			)
			if err != nil {
				return nil, fmt.Errorf("failed to get kubernetes runtime instance ID: %w", err)
			}
			runtimeNames = append(runtimeNames, *runtime.Name)
		}
		for _, rName := range runtimeNames {
			// if the workload instance is using a cluster that already has an
			// instance for this definition, return error
			if rName == *kubernetesRuntimeInstance.Name {
				return nil, errors.New("only one workload instance per Kubernetes runtime may be deployed when a Kubernetes namespace is included in the workload definition YAMLDocument\nif you would like to deploy this workload to the same Kubernetes runtime (and continue to manage namespaces), you will need a new workload definition that uses a different namespace")
			}
		}
	}

	// construct workload instance object
	workloadInstance := api_v0.WorkloadInstance{
		Instance: api_v0.Instance{
			Name: workloadInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		WorkloadDefinitionID:        workloadDefinition.ID,
	}

	// create workload instance
	createdWorkloadInstance, err := client_v0.CreateWorkloadInstance(
		apiClient,
		apiEndpoint,
		&workloadInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create workload instance in threeport API: %w", err)
	}

	// construct workload instance config
	createdWorkloadInstanceConfig := &WorkloadInstanceConfig{
		WorkloadInstance: WorkloadInstanceValues{
			Name:                      createdWorkloadInstance.Name,
			KubernetesRuntimeInstance: workloadInstanceValues.KubernetesRuntimeInstance,
			WorkloadDefinition:        workloadInstanceValues.WorkloadDefinition,
			Status:                    util.Ptr(string(*createdWorkloadInstance.Status)),
			Age:                       util.Ptr(util.GetAgeFormatted(createdWorkloadInstance.CreatedAt)),
		},
	}

	return createdWorkloadInstanceConfig, nil
}

// Replace updates the entire workload instance object in the Threeport API.
// This is a full replacement of all fields in the workload instance object.
// This function takes a name parameter to identify the workload instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (w *WorkloadInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*WorkloadInstanceConfig, error) {
	workloadInstanceValues := w.WorkloadInstance
	// validate config
	if err := w.Validate(); err != nil {
		return nil, fmt.Errorf("invalid workload instance config: %w", err)
	}

	// get existing workload instance by name
	existingWorkloadInstance, err := client_v0.GetWorkloadInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find workload instance with name %s: %w", name, err)
	}

	// ensure user is not trying to move the workload to a different runtime
	kubernetesRuntimeInstance, moved, err := getKubernetesRuntimeInstanceAndCheckId(
		apiClient,
		apiEndpoint,
		workloadInstanceValues.KubernetesRuntimeInstance,
		existingWorkloadInstance.KubernetesRuntimeInstanceID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}
	if moved {
		return nil, fmt.Errorf(
			"a workload may not be moved from its current runtime to %s - if %[1]s runtime needs this workload, create a new instance there instead",
			*kubernetesRuntimeInstance.Name,
		)
	}

	// get workload definition by name
	workloadDefinition, err := client_v0.GetWorkloadDefinitionByName(
		apiClient,
		apiEndpoint,
		*workloadInstanceValues.WorkloadDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get workload definition by name %s: %w", *workloadInstanceValues.WorkloadDefinition.Name, err)
	}

	// construct updated workload instance object
	updatedWorkloadInstance := &api_v0.WorkloadInstance{
		Common: api_v0.Common{
			ID: existingWorkloadInstance.ID,
		},
		Instance: api_v0.Instance{
			Name: workloadInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		WorkloadDefinitionID:        workloadDefinition.ID,
	}

	// replace workload instance
	replacedWorkloadInstance, err := client_v0.ReplaceWorkloadInstance(
		apiClient,
		apiEndpoint,
		updatedWorkloadInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace workload instance in threeport API: %w", err)
	}

	// construct updated workload instance config
	updatedWorkloadInstanceConfig := &WorkloadInstanceConfig{
		WorkloadInstance: WorkloadInstanceValues{
			Name:                      replacedWorkloadInstance.Name,
			KubernetesRuntimeInstance: workloadInstanceValues.KubernetesRuntimeInstance,
			WorkloadDefinition:        workloadInstanceValues.WorkloadDefinition,
			Status:                    util.Ptr(string(*replacedWorkloadInstance.Status)),
			Age:                       util.Ptr(util.GetAgeFormatted(replacedWorkloadInstance.CreatedAt)),
		},
	}

	return updatedWorkloadInstanceConfig, nil
}

// Delete deletes a workload instance from the Threeport API.
func (w *WorkloadInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*WorkloadInstanceConfig, error) {
	workloadInstanceValues := w.WorkloadInstance
	// get workload instance by name
	workloadInstance, err := client_v0.GetWorkloadInstanceByName(
		apiClient,
		apiEndpoint,
		*workloadInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find workload instance with name %s: %w", *workloadInstanceValues.Name, err)
	}

	// delete workload instance
	deletedWorkloadInstance, err := client_v0.DeleteWorkloadInstance(
		apiClient,
		apiEndpoint,
		*workloadInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete workload instance from Threeport API: %w", err)
	}

	// wait for workload instance to be deleted
	util.Retry(60, 1, func() error {
		if _, err := client_v0.GetWorkloadInstanceByName(apiClient, apiEndpoint, *workloadInstanceValues.Name); err == nil {
			return errors.New("workload instance not deleted")
		}
		return nil
	})

	// construct deleted workload instance config
	deletedWorkloadInstanceConfig := &WorkloadInstanceConfig{
		WorkloadInstance: WorkloadInstanceValues{
			Name: deletedWorkloadInstance.Name,
		},
	}

	return deletedWorkloadInstanceConfig, nil
}

// Validate validates inputs to create workload instances.
func (w *WorkloadInstanceConfig) Validate() error {
	workloadInstanceValues := w.WorkloadInstance
	multiError := util.MultiError{}

	// ensure name is set
	if workloadInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// ensure workload definition name is set
	if workloadInstanceValues.WorkloadDefinition == nil || workloadInstanceValues.WorkloadDefinition.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: WorkloadDefinition.Name"))
	}

	return multiError.Error()
}
